In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
data = pd.read_csv('Data Training Testing.csv')

In [5]:
# Random seed for reproducibility
seed = 10
np.random.seed(seed)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4962 entries, 0 to 4961
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [7]:
data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [8]:
data.isna().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [9]:
data.shape

(4962, 133)

In [10]:
data.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4962.000000  4962.000000           4962.000000          4962.000000   
mean      0.138049     0.160016              0.021967             0.045143   
std       0.344986     0.366658              0.146590             0.207639   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4962.000000  4962.000000  4962.000000   4962.000000  4962.000000   
mean      0.021967     0.162233     0.139057      0.045143     0.045143   
std       0.146590     0.368702     0.346041      0.207639     0.207639   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4962.000000  ...         4962.000000  4962.000000  4962.000000   
mean           0.021967  ...            0.021967     0.021967     0.021967   
std            0.146590  ...            0.146590     0.146590     0.146590   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4962.000000          4962.000000           4962.000000   
mean       0.023378             0.023176              0.023176   
std        0.151115             0.150478              0.150478   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4962.000000  4962.000000           4962.000000   
mean             0.023176     0.023176              0.023378   
std              0.150478     0.150478              0.151115   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4962.000000  
mean            0.023176  
std             0.150478  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

##Train and Test Data

In [11]:
X = data.copy()
y = X.pop('prognosis')

In [12]:
X.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                   0           0         0             0   
1                   0           0         0             0   
2                   0           0         0             0   
3                   0           0         0             0   
4                   0           0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   red_sore_around_nose  yellow_crust_ooze  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  

[5 rows x 132 columns]

In [13]:
y.head()

0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
Name: prognosis, dtype: object

In [14]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.75, shuffle = False)

#input_shape = [X_train.shape[1]]

In [15]:
X_train.shape

(3721, 132)

In [16]:
y_train

0                   Fungal infection
1                   Fungal infection
2                   Fungal infection
3                   Fungal infection
4                   Fungal infection
                    ...             
3716                     Common Cold
3717                       Pneumonia
3718    Dimorphic hemmorhoids(piles)
3719                    Heart attack
3720                  Varicose veins
Name: prognosis, Length: 3721, dtype: object

In [17]:
X_valid.shape

(1241, 132)

In [18]:
y_valid.shape

(1241,)

In [19]:
label_encoder = LabelEncoder()
y_train_label = label_encoder.fit_transform(y_train)
y_valid_label = label_encoder.transform(y_valid)

In [20]:
y_train_cat = tf.keras.utils.to_categorical(y_train_label, num_classes=42)
y_valid_cat = tf.keras.utils.to_categorical(y_valid_label, num_classes=42)

#Define Model

In [21]:
# the new model we made
def baseline_model():
  model = tf.keras.Sequential([
      tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(42, activation='softmax')
      ])

  model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

  history = model.fit(
    X_train, y_train_cat,
    validation_data=(X_valid, y_valid_cat),
    batch_size=32,
    epochs=100
)

  return model

In [22]:
if __name__ == '__main__':
  model = baseline_model()
  model.save("model.h5")

c:\Users\ASUS\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 8s 20ms/step - accuracy: 0.3747 - loss: 3.1346 - val_accuracy: 1.0000 - val_loss: 0.3575
Epoch 2/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9919 - loss: 0.3233 - val_accuracy: 1.0000 - val_loss: 0.0130
Epoch 3/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9996 - loss: 0.0455 - val_accuracy: 1.0000 - val_loss: 0.0034
Epoch 4/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9998 - loss: 0.0199 - val_accuracy: 1.0000 - val_loss: 0.0018
Epoch 5/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 1.0000 - loss: 0.0128 - val_accuracy: 1.0000 - val_loss: 9.1111e-04
Epoch 6/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9998 - loss: 0.0091 - val_accuracy: 1.0000 - val_loss: 5.7582e-04
Epoch 7/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 1.0000 - loss: 0.0057 - val_accuracy: 1.0000 - val_loss: 4.2954e-04
Epoch 8/100
117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 1.0000 - loss: 0.0

In [25]:
disease_names = label_encoder.classes_
list(disease_names)

['(vertigo) Paroymsal  Positional Vertigo',
 'AIDS',
 'Acne',
 'Alcoholic hepatitis',
 'Allergy',
 'Arthritis',
 'Bronchial Asthma',
 'Cervical spondylosis',
 'Chicken pox',
 'Chronic cholestasis',
 'Common Cold',
 'Dengue',
 'Diabetes',
 'Dimorphic hemmorhoids(piles)',
 'Drug Reaction',
 'Fungal infection',
 'GERD',
 'Gastroenteritis',
 'Heart attack',
 'Hepatitis B',
 'Hepatitis C',
 'Hepatitis D',
 'Hepatitis E',
 'Hypertension',
 'Hyperthyroidism',
 'Hypoglycemia',
 'Hypothyroidism',
 'Impetigo',
 'Jaundice',
 'Malaria',
 'Migraine',
 'Osteoarthristis',
 'Paralysis (brain hemorrhage)',
 'Peptic ulcer diseae',
 'Pneumonia',
 'Psoriasis',
 'Tuberculosis',
 'Typhoid',
 'Urinary tract infection',
 'Varicose veins',
 'hepatitis A']

In [28]:
#Input the symptoms of fungal infection
sample_input = np.array([
1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
sample_input = sample_input.reshape(1, -1)

In [29]:
predictions = model.predict(sample_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


In [30]:
predictions

array([[3.16661679e-16, 4.47921566e-13, 2.60626264e-13, 1.98558604e-13,
        1.58146594e-13, 2.23688505e-15, 1.07743804e-13, 4.97755862e-13,
        1.73170137e-12, 5.57302236e-15, 6.04628599e-19, 1.16487560e-12,
        1.21242710e-13, 3.89215536e-15, 6.82842116e-14, 1.00000000e+00,
        1.55989759e-19, 1.30227045e-18, 8.53715111e-17, 3.82877757e-13,
        2.01794622e-14, 5.82819625e-21, 4.84208494e-18, 7.01584765e-19,
        1.33638001e-12, 1.61115099e-13, 5.54241386e-13, 2.30868753e-12,
        1.56084875e-13, 2.08833954e-13, 2.38615322e-15, 1.99188946e-14,
        2.49098721e-20, 7.51260711e-15, 1.31692024e-14, 1.84632821e-12,
        2.40335854e-19, 1.38622007e-14, 4.54131897e-16, 2.36180166e-15,
        5.75450036e-20, 1.72248094e-16]], dtype=float32)

In [31]:
# Map the predicted label to the disease name
predicted_label_index = np.argmax(predictions, axis=1)
predicted_label_index

array([15], dtype=int64)

In [32]:
predicted_disease_name = disease_names[predicted_label_index]
predicted_disease_name

array(['Fungal infection'], dtype=object)

In [33]:
#Input the symptoms of allergy
sample_input = np.array([
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
])
sample_input = sample_input.reshape(1, -1)

In [34]:
input = np.array(X_train.iloc[11,:])
input = input.reshape(1,-1)

In [36]:
predictions = model.predict(input)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step


array([[6.2397581e-13, 8.5620948e-11, 8.2435128e-11, 3.2242936e-18,
        1.0000000e+00, 2.6843135e-11, 4.9580869e-13, 4.7525994e-10,
        6.2129518e-10, 7.1802183e-13, 1.3164294e-12, 2.6699519e-13,
        6.2351898e-13, 1.3324761e-11, 2.0655582e-12, 8.6823132e-10,
        3.2909602e-11, 1.2888281e-10, 6.2236606e-14, 2.2512957e-12,
        2.2841854e-12, 2.1337966e-14, 6.6986923e-16, 2.6290485e-14,
        3.8225920e-12, 3.2279935e-13, 5.4504592e-11, 1.4986377e-11,
        3.1131836e-17, 1.0264425e-10, 9.8498575e-14, 8.1673539e-12,
        1.5069529e-11, 5.4097251e-11, 5.9517648e-11, 5.9339651e-12,
        3.2181422e-15, 2.2002503e-10, 1.1120845e-10, 1.5630310e-11,
        5.9697665e-17, 1.7449895e-13]], dtype=float32)

In [37]:
predicted_label_index = np.argmax(predictions, axis=1)
predicted_label_index

array([4], dtype=int64)

In [38]:
predicted_disease_name = disease_names[predicted_label_index]
predicted_disease_name

array(['Allergy'], dtype=object)